### ISSUE TITLE
Can't use union() function

### ISSUE THREAD

**Issue by AmiK2001** [viralogic/py-enumerable#20]
When i am running this code:
```python
from py_linq import Enumerable
students1 = Enumerable([{'name': "John", 'mark': 55}, {'name': "Jerry", 'mark': 55}])
students2 = Enumerable([{'name': "John", 'mark': 55}, {'name': "Jared", 'mark': 70}])

print(students1.union(students2))
```

I am getting this error:
```python
Traceback (most recent call last):
  File "c:\Users\AmiK\Documents\Projects\linq_test.py", line 5, in <module>
    print(students1.union(students2))
  File "C:\Users\AmiK\Anaconda3\lib\site-packages\py_linq\py_linq3.py", line 462, in union
    return self.concat(enumerable).distinct(key)
  File "C:\Users\AmiK\Anaconda3\lib\site-packages\py_linq\py_linq3.py", line 341, in distinct
    return Enumerable3(self.group_by(key=key).select(lambda g: g.first()).to_list())
  File "C:\Users\AmiK\Anaconda3\lib\site-packages\py_linq\py_linq3.py", line 322, in group_by
    ordered = sorted(self, key=key)
TypeError: '<' not supported between instances of 'dict' and 'dict'
```

**Comment by AmiK2001** [comment]
I thought and understood that this method cannot be used in this way.
