### ISSUE TITLE
Field name not found, throw exception

### ISSUE THREAD

**Issue by ksusanto** [viralogic/py-enumerable#83]
aa = Enumerable([{'numbertag': 1, 'numberdesign': 1, 'notes': None, 'status': 128, 'plcstart': '2023-11-10 21:00:02', 'plcstop': '2023-11-10 21:01:04', 'groupuid': 'GROUP:3303', 'tagtype': 'CYCLETIME'},{'numbertag': 5, 'numberdesign': 5, 'notes': '', 'status': 0}, {'numbertag': 1, 'numberdesign': 1, 'notes': None, 'status': 8, 'plcstart': '2023-11-10 20:59:04', 'plcstop': '2023-11-10 20:59:15', 'groupuid': 'GROUP:3305', 'tagtype': 'GROUPOP'}])

bb = aa.where(lambda x: x['tagtype'] != 'CYCLETIME' and x['status'] & 32 != 32).to_list()

in py-linq==1.3.0, it works but not in 1.4.0.  it throw the exception
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\_Envision\venv\dataprocessor\lib\site-packages\py_linq\py_linq.py", line 90, in to_list
    return [x for x in self]
  File "c:\_Envision\venv\dataprocessor\lib\site-packages\py_linq\py_linq.py", line 90, in <listcomp>
    return [x for x in self]
  File "c:\_Envision\venv\dataprocessor\lib\site-packages\py_linq\core.py", line 103, in __iter__
    for index, item in enumerate(self._data):
  File "<string>", line 1, in <lambda>
KeyError: 'tagtype'

**Comment by viralogic** [comment]
**Not a bug — working as intended.**

The `KeyError` is expected Python behavior. The second dict in the source data has no `tagtype` key, so `x[tagtype]` raises `KeyError` — this is the same with or without py-linq:

```python
{"numbertag": 5, "numberdesign": 5, "notes": "", "status": 0}["tagtype"]
# KeyError: 'tagtype'
```

The user's lambda can be fixed by using `.get()`:

```python
aa.where(lambda x: x.get('tagtype', '') != 'CYCLETIME' and x['status'] & 32 != 32).to_list()
```

Closing as "works as intended." The library correctly surfaces the `KeyError` from the predicate — hiding it would mask real data bugs.

**Comment by viralogic** [comment]
Closing — KeyError is expected Python behavior for missing dict keys. See comment above for the fix.
